[package]
name = "tinyslam"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.15.0"
flume = "0.11.0"
pollster = "0.3.0"
wgpu = "0.20.0"
tiny_wgpu = "0.1.7"
seq-macro = "0.3"
const_format = "0.2.32"
