[package]
name = "orbslam_gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.15.0"
flume = "0.11.0"
pollster = "0.3.0"
wgpu = "0.19.3"
tiny_wgpu = { path = "../tiny_wgpu" }